"""Initial migration: 12 entities with indexes and constraints

Revision ID: e46d7227656f
Revises: 
Create Date: 2025-11-13 11:50:55.108973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e46d7227656f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_email', 'admin_user', ['email'], unique=False)
    op.create_index('idx_admin_is_active', 'admin_user', ['is_active'], unique=False)
    op.create_index(op.f('ix_admin_user_email'), 'admin_user', ['email'], unique=True)
    op.create_index(op.f('ix_admin_user_is_active'), 'admin_user', ['is_active'], unique=False)
    op.create_table('candidate',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('account_status', sa.Enum('UNVERIFIED', 'ACTIVE', 'SUSPENDED', name='accountstatus'), nullable=False),
    sa.Column('submission_status', sa.Enum('INCOMPLETE', 'SUBMITTED', 'UNDER_REVIEW', 'REVIEWED', name='submissionstatus'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_decision', sa.Enum('ELIMINATED', 'HIRED', name='finaldecision'), nullable=True),
    sa.Column('final_decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidate_account_status', 'candidate', ['account_status'], unique=False)
    op.create_index('idx_candidate_created_at', 'candidate', ['created_at'], unique=False)
    op.create_index('idx_candidate_email', 'candidate', ['email'], unique=False)
    op.create_index('idx_candidate_submission_status', 'candidate', ['submission_status'], unique=False)
    op.create_index(op.f('ix_candidate_account_status'), 'candidate', ['account_status'], unique=False)
    op.create_index(op.f('ix_candidate_email'), 'candidate', ['email'], unique=True)
    op.create_index(op.f('ix_candidate_submission_status'), 'candidate', ['submission_status'], unique=False)
    op.create_table('audit_log',
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('action_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_type', 'audit_log', ['action_type', 'created_at'], unique=False)
    op.create_index('idx_audit_admin_id', 'audit_log', ['admin_user_id', 'created_at'], unique=False)
    op.create_index('idx_audit_candidate_id', 'audit_log', ['candidate_id', 'created_at'], unique=False)
    op.create_index('idx_audit_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_action_type'), 'audit_log', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_log_admin_user_id'), 'audit_log', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_candidate_id'), 'audit_log', ['candidate_id'], unique=False)
    op.create_table('document',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('RESUME', 'COVER_LETTER', name='documenttype'), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('file_size_bytes <= 10485760', name='check_file_size_max_10mb'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'document_type', name='unique_candidate_document_type')
    )
    op.create_index('idx_document_candidate_id', 'document', ['candidate_id'], unique=False)
    op.create_index('idx_document_type', 'document', ['candidate_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_document_candidate_id'), 'document', ['candidate_id'], unique=False)
    op.create_table('interview_prompt',
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('time_limit_seconds IS NULL OR (time_limit_seconds >= 30 AND time_limit_seconds <= 300)', name='check_time_limit_range'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prompt_is_active', 'interview_prompt', ['is_active', 'sequence_order'], unique=False)
    op.create_index('idx_prompt_sequence_order', 'interview_prompt', ['sequence_order'], unique=False)
    op.create_index(op.f('ix_interview_prompt_is_active'), 'interview_prompt', ['is_active'], unique=False)
    op.create_index(op.f('ix_interview_prompt_sequence_order'), 'interview_prompt', ['sequence_order'], unique=True)
    op.create_table('menu',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_menu_created_at', 'menu', ['created_at'], unique=False)
    op.create_index('idx_menu_is_active', 'menu', ['is_active'], unique=False)
    op.create_index(op.f('ix_menu_is_active'), 'menu', ['is_active'], unique=False)
    op.create_table('menu_category',
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_id', 'category_name', name='unique_menu_category_name'),
    sa.UniqueConstraint('menu_id', 'sequence_order', name='unique_menu_category_order')
    )
    op.create_index('idx_category_menu_id', 'menu_category', ['menu_id', 'sequence_order'], unique=False)
    op.create_index('idx_category_sequence_order', 'menu_category', ['menu_id', 'sequence_order'], unique=False)
    op.create_index(op.f('ix_menu_category_menu_id'), 'menu_category', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_category_sequence_order'), 'menu_category', ['sequence_order'], unique=False)
    op.create_table('video_recording',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('transcription_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'UNAVAILABLE', name='transcriptionstatus'), nullable=False),
    sa.Column('transcription_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcription_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcription_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds <= 300', name='check_duration_max_5min'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['interview_prompt.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'prompt_id', name='unique_candidate_prompt_response')
    )
    op.create_index('idx_video_candidate_id', 'video_recording', ['candidate_id'], unique=False)
    op.create_index('idx_video_candidate_prompt', 'video_recording', ['candidate_id', 'prompt_id'], unique=False)
    op.create_index('idx_video_transcription_status', 'video_recording', ['transcription_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_video_recording_candidate_id'), 'video_recording', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_video_recording_prompt_id'), 'video_recording', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_video_recording_transcription_status'), 'video_recording', ['transcription_status'], unique=False)
    op.create_table('dish',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('dish_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_urls', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dish_category_id', 'dish', ['category_id'], unique=False)
    op.create_index('idx_dish_is_active', 'dish', ['is_active'], unique=False)
    op.create_index('idx_dish_name', 'dish', ['dish_name'], unique=False)
    op.create_index(op.f('ix_dish_category_id'), 'dish', ['category_id'], unique=False)
    op.create_index(op.f('ix_dish_is_active'), 'dish', ['is_active'], unique=False)
    op.create_table('transcript',
    sa.Column('video_recording_id', sa.UUID(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='check_confidence_score_range'),
    sa.ForeignKeyConstraint(['video_recording_id'], ['video_recording.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transcript_confidence_score', 'transcript', ['confidence_score'], unique=False)
    op.create_index('idx_transcript_video_recording_id', 'transcript', ['video_recording_id'], unique=False)
    op.create_index(op.f('ix_transcript_video_recording_id'), 'transcript', ['video_recording_id'], unique=True)
    op.create_table('feedback',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('should_eliminate', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('comment_text IS NULL OR length(comment_text) <= 500', name='check_comment_length'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='check_rating_range'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'dish_id', name='unique_candidate_dish_feedback')
    )
    op.create_index('idx_feedback_candidate_dish', 'feedback', ['candidate_id', 'dish_id'], unique=False)
    op.create_index('idx_feedback_candidate_id', 'feedback', ['candidate_id'], unique=False)
    op.create_index('idx_feedback_dish_id', 'feedback', ['dish_id'], unique=False)
    op.create_index('idx_feedback_rating', 'feedback', ['dish_id', 'rating'], unique=False)
    op.create_index(op.f('ix_feedback_candidate_id'), 'feedback', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_feedback_dish_id'), 'feedback', ['dish_id'], unique=False)
    op.create_table('proposed_dish',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('original_dish_id', sa.UUID(), nullable=False),
    sa.Column('proposal_description', sa.Text(), nullable=True),
    sa.Column('photo_urls', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('array_length(photo_urls, 1) <= 5 AND array_length(photo_urls, 1) >= 1', name='check_photo_urls_count'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_dish_id'], ['dish.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proposal_candidate_id', 'proposed_dish', ['candidate_id'], unique=False)
    op.create_index('idx_proposal_dish_id', 'proposed_dish', ['original_dish_id'], unique=False)
    op.create_index('idx_proposal_feedback_id', 'proposed_dish', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_proposed_dish_candidate_id'), 'proposed_dish', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_proposed_dish_feedback_id'), 'proposed_dish', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_proposed_dish_original_dish_id'), 'proposed_dish', ['original_dish_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposed_dish_original_dish_id'), table_name='proposed_dish')
    op.drop_index(op.f('ix_proposed_dish_feedback_id'), table_name='proposed_dish')
    op.drop_index(op.f('ix_proposed_dish_candidate_id'), table_name='proposed_dish')
    op.drop_index('idx_proposal_feedback_id', table_name='proposed_dish')
    op.drop_index('idx_proposal_dish_id', table_name='proposed_dish')
    op.drop_index('idx_proposal_candidate_id', table_name='proposed_dish')
    op.drop_table('proposed_dish')
    op.drop_index(op.f('ix_feedback_dish_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_candidate_id'), table_name='feedback')
    op.drop_index('idx_feedback_rating', table_name='feedback')
    op.drop_index('idx_feedback_dish_id', table_name='feedback')
    op.drop_index('idx_feedback_candidate_id', table_name='feedback')
    op.drop_index('idx_feedback_candidate_dish', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_transcript_video_recording_id'), table_name='transcript')
    op.drop_index('idx_transcript_video_recording_id', table_name='transcript')
    op.drop_index('idx_transcript_confidence_score', table_name='transcript')
    op.drop_table('transcript')
    op.drop_index(op.f('ix_dish_is_active'), table_name='dish')
    op.drop_index(op.f('ix_dish_category_id'), table_name='dish')
    op.drop_index('idx_dish_name', table_name='dish')
    op.drop_index('idx_dish_is_active', table_name='dish')
    op.drop_index('idx_dish_category_id', table_name='dish')
    op.drop_table('dish')
    op.drop_index(op.f('ix_video_recording_transcription_status'), table_name='video_recording')
    op.drop_index(op.f('ix_video_recording_prompt_id'), table_name='video_recording')
    op.drop_index(op.f('ix_video_recording_candidate_id'), table_name='video_recording')
    op.drop_index('idx_video_transcription_status', table_name='video_recording')
    op.drop_index('idx_video_candidate_prompt', table_name='video_recording')
    op.drop_index('idx_video_candidate_id', table_name='video_recording')
    op.drop_table('video_recording')
    op.drop_index(op.f('ix_menu_category_sequence_order'), table_name='menu_category')
    op.drop_index(op.f('ix_menu_category_menu_id'), table_name='menu_category')
    op.drop_index('idx_category_sequence_order', table_name='menu_category')
    op.drop_index('idx_category_menu_id', table_name='menu_category')
    op.drop_table('menu_category')
    op.drop_index(op.f('ix_menu_is_active'), table_name='menu')
    op.drop_index('idx_menu_is_active', table_name='menu')
    op.drop_index('idx_menu_created_at', table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_interview_prompt_sequence_order'), table_name='interview_prompt')
    op.drop_index(op.f('ix_interview_prompt_is_active'), table_name='interview_prompt')
    op.drop_index('idx_prompt_sequence_order', table_name='interview_prompt')
    op.drop_index('idx_prompt_is_active', table_name='interview_prompt')
    op.drop_table('interview_prompt')
    op.drop_index(op.f('ix_document_candidate_id'), table_name='document')
    op.drop_index('idx_document_type', table_name='document')
    op.drop_index('idx_document_candidate_id', table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_audit_log_candidate_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_admin_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action_type'), table_name='audit_log')
    op.drop_index('idx_audit_created_at', table_name='audit_log')
    op.drop_index('idx_audit_candidate_id', table_name='audit_log')
    op.drop_index('idx_audit_admin_id', table_name='audit_log')
    op.drop_index('idx_audit_action_type', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_candidate_submission_status'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_email'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_account_status'), table_name='candidate')
    op.drop_index('idx_candidate_submission_status', table_name='candidate')
    op.drop_index('idx_candidate_email', table_name='candidate')
    op.drop_index('idx_candidate_created_at', table_name='candidate')
    op.drop_index('idx_candidate_account_status', table_name='candidate')
    op.drop_table('candidate')
    op.drop_index(op.f('ix_admin_user_is_active'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_email'), table_name='admin_user')
    op.drop_index('idx_admin_is_active', table_name='admin_user')
    op.drop_index('idx_admin_email', table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
